### ISSUE TITLE
How to decrease the whole game's size?

### ISSUE THREAD

**Issue by misudashi** [russs123/Platformer#4]
Hello. So I have a little problem because I have a small screen. 
Sadly, I am not able to view the entire game when i start it. 

I watched the tutorials, and I understood some things. What I tried is modifying:

The variables "screen_width" and "screen_height" to 500 intead of 1000 ( / 2)
The variable title_size to 25 instead of 50 ( / 2 )
But now, the buttons are in the wrong place and the character is way too big. Maybe you think of a way so I could properly decrease the size of the whole game without ruining the assets ?

Thank you for reading, I hope you have a good day. -Misudashi

PS: Here is a screenshot of what it looks in-game after modifying those two variables.
![image](https://user-images.githubusercontent.com/76494310/150649824-ea24bb3a-fa10-4691-8bb8-fe156d4d89d1.png)
![image](https://user-images.githubusercontent.com/76494310/150649835-7f89e9cf-eff6-4dda-bad4-8ff16d5ea472.png)

I had the same problem with the level editor but I just reduced the tile_size and everything was fine.

**Comment by russs123** [comment]
Hello. You can scale all of the items as they are created, this is covered in the tutorial videos.
